CREATE TABLE IF NOT EXISTS `users` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `username` TEXT NOT NULL UNIQUE,
  `password` TEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `rooms` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `code` TEXT NOT NULL UNIQUE,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `room_members` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `room_id` INTEGER NOT NULL,
  `username` TEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `songs` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `song_number` TEXT NOT NULL UNIQUE,
  `title` TEXT NOT NULL,
  `artist` TEXT NOT NULL,
  `source_type` TEXT NOT NULL,
  `video_source` TEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);
